name: دانلود فایل دلخواه شما با نت ملی

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'لینک مستقیم فایل مورد نظر'
        required: true
        type: string

permissions:
  contents: write

jobs:
  download-and-split:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد مخزن
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: نصب 7z
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: دانلود فایل از لینک
        run: |
          git rm archive.7z.* 2>/dev/null || true; git commit -m ""; git push;
